### ISSUE TITLE
windows building failed

### ISSUE THREAD

**Issue by liquidzym** [roxlu/screen_capture#1]
broken at the build_win_dependencies.sh line611:cmake:command not found
failed to setup glfw

**Comment by roxlu** [comment]
Have you installed cmake ~3.x and added it to your path variable?

**Comment by liquidzym** [comment]
sure,i'm using cmake3.2.1,the cmake bin in my path variable,win8.1,but i'll double check on that

**Comment by roxlu** [comment]
I just did a clean clone on win 8.1 and VS2012 and that worked. Can you maybe do a new clone and paste all output on gist? Or give me a shout on Skype so we can walk this through.
Thanks

**Comment by liquidzym** [comment]
ok,my bad,i added wrong version of cmake in my path var which doesn't exist
everything works now except the test_opengl wouldn't run,failed to duplicated the output
failed to setup the screencapture,but that's another issue. btw,i only installed the vs2013
cheers.
alex
